### ISSUE TITLE
Publish to many queue group?

### ISSUE THREAD

**Issue by zhaoyao91** [hemerajs/hemera#122]
According to the docs, we can publish to many subscriber, or publish to only one queue group, but, how to publish to many queue group? 

In other word, there are many roles listen to the same topic and react differently, but we wish to clustering a role with many instances, so, a publication should be pushed to all the subscriber roles, but only one instance of each role will receive it.

**Comment by zhaoyao91** [comment]
I have had a quick view of the source code, guessing that I may code as below:
```
// group-1 with many instances
hemera.add({
  $queue: 'group-1'
  topic: 'sth-happened'
}, handler)

// group-2 with many instances
hemera.add({
  $queue: 'group-2'
  topic: 'sth-happened'
}, handler)

hemera.act({
  $pubsub: true,
  topic: 'sth-hanppened'
})
```
Does this implement what I issued before?

Thanks.

**Comment by StarpTech** [comment]
You can't publish to a specific queue because many subscribers builds a queue group. The publisher is not aware of that. If you have one queue group and many instances (default) the request will be load balanced. If you have many queue groups with the same topic the request will arrive one instance doesnt matter how much this service is scaled.

**Comment by StarpTech** [comment]
Closed due to inactivity.
