### ISSUE TITLE
Feature Request: Better Pre/Post Validation Logs

### ISSUE THREAD

**Issue by pward123** [hemerajs/hemera#172]
## Better Pre/Post Validation Logs
The logging of pre/post validation errors is not detailed enough to troubleshoot problems.

## Steps to Reproduce
See https://github.com/pward123/hemera-pre-validation-example/blob/master/README.md

## Context

- [ ] nats-hemera (core)
- [ ] hemera-zipkin
- [ ] hemera-store
- [ ] hemera-stats
- [ ] hemera-rabbitmq
- [ ] hemera-nsq
- [ ] hemera-arango-store
- [ ] hemera-sql-store
- [ ] hemera-elasticsearch
- [ ] hemera-couchbase-store
- [ ] hemera-mongo-store
- [X] hemera-joi
- [ ] hemera-parambulator
- [ ] hemera-msgpack
- [ ] hemera-avro
- [ ] hemera-redis-cache
- [ ] hemera-jwt-auth

## Your Environment
- NATS: 0.7.24
- Hemera: 2.4.0
- NodeJs: 8.6.0
- macos 10.12.6

**Comment by StarpTech** [comment]
Hi @pward123 thank you for the great example. I think we cannot solve it because the error is raised by the middleware and the location will be always useless for a user as a library developer it tells me correct informations (releated extension, plugin). I would like to know which informations are you expect to get ? All errors are responded to the callee.

If you want to know which call was responsible you can handle that in the act call or use the `clientResponseError` event

```js
hemera.on('clientResponseError', function(err) {
  console.log(this.trace$, err.name)
})
```

```
```

**Comment by StarpTech** [comment]
But I found an inconsistency. The `hops` property where involved services are tracked is not set when an extension error is thrown. This could be very helpful.

**Comment by StarpTech** [comment]
Here https://github.com/hemerajs/hemera/pull/173

**Comment by pward123** [comment]
LGTM - Closing

Thanks!
