### ISSUE TITLE
Handled errors are being logged in the client

### ISSUE THREAD

**Issue by leolower** [hemerajs/hemera#206]
## Description
Errors are logged in the client even if they are handled directly.

## Steps to Reproduce
1. **Service A** makes a call to **service B**. 
2. **B** responds with an error or simply throws.
3. **A** catches the error and deals with it.

## Actual Result
**The error is logged even though it was handled in the client**

## Expected Result
Unhandled errors should probably crash the app. Handled errors are not logged (or explicitly logged by the handled). Another option would be to configure log levels so that they ca be ignored.

## Context
- [x] nats-hemera (core)
- [ ] hemera-zipkin
- [x] hemera-store
- [x] hemera-stats
- [ ] hemera-rabbitmq
- [ ] hemera-nsq
- [ ] hemera-elasticsearch
- [x] hemera-joi
- [ ] hemera-msgpack
- [ ] hemera-avro
- [ ] hemera-jwt-auth

## Your Environment
- NATS: latest docker image available
- Hemera: 3.5.1
- NodeJs: 8.9
- Operating System and version: Ubuntu 17.10

**Comment by StarpTech** [comment]
Hi @leolower thanks for reporting.
At the moment an error is logged when the client receives a response error. This is not ideal because you will log an error even when the application will handle it correctly. We should remove it. That's the only point.

> Unhandled errors should probably crash the app

This is valid for `thrown` errors with `callback-style` with `async/await` or promises it will only return a rejected promise.

**Comment by StarpTech** [comment]
Released with 5.4.2
