### ISSUE TITLE
Direct communication ?

### ISSUE THREAD

**Issue by danielo515** [hemerajs/hemera#212]
Hello,

I want to know if Hemera supports direct communication through microservices.
I want to know if:

- Can services detect that they are on the same machine ?
- Can services fetch the IP of another one and perform a direct request ?

Thanks in advance

**Comment by StarpTech** [comment]
Hi @danielo515 

> I want to know if Hemera supports direct communication through microservices.

No, NATS is the central nervous system. Due to the simplicity of NATS, we don't see the need for this. Therefore we can reduce much complexity when the handle everything equally.

> Can services detect that they are on the same machine ?
> Can services fetch the IP of another one and perform a direct request ?

Services should just communicate with each other they shouldn't know their physical location. That's the big advantage of service-discovery. NATS provide both routing and service-dicovery.

https://nats.io/documentation/

**Comment by danielo515** [comment]
Yes I was guessing that. However other frameworks also use a centralized communication mechanism (or maybe some for discovery) but they also provide direct communication. Hydra and moleculer allow this, not sure if Seneca does it too.

I was expecting this answer though. 

Regards

**Comment by StarpTech** [comment]
Sure, but we don't have a need for this. We trust in a well tested system and provide a lightweight abstraction on top of it. Developing a generic interface is much more complex and it's not worth.
