### ISSUE TITLE
Proper way to test services

### ISSUE THREAD

**Issue by pocesar** [hemerajs/hemera#53]
I'm missing the proper way to test the services (the aither repo doesn't have any besides the load test), and couldn't find a definitive answer. In express, I used superagent, which made the REST testing somewhat easy, and doesn't need to listen on a port

**Comment by StarpTech** [comment]
Hi @pocesar we use NATS as transport layer so we cant emulate it for tests but you can look in the test directory there you can a very simple way to testing your services. There is a package called `hemera-testsuite` with that you can start and stop the server. Thanks.

**Comment by StarpTech** [comment]
@prcesar it's the same scenario as with a http api. You should do unit tests to test your business code. You should do integration tests to test your stack. How to do integration tests you can see in the tests directory or in the documentation. Unit tests are independent from the used framework. If you have services which calls other services you have to mock that interface in your unit tests. I hope it is clear otherwise refine your question. Thanks!

**Comment by StarpTech** [comment]
If you have any ideas to create test utilities do not hesitate to make an approach. Please reopen when needed.

**Comment by acehko** [comment]
Hi @StarpTech 
Since hemera is used only with NATS, and is not transport independent, why not make the `nats` package a dependency of `nats-hemera`? Or make it optional. That way it would be a lot easier to test without the need to run nats. Then we could use something like `hemera.start()` to connect to nats.

**Comment by pocesar** [comment]
@StarpTech yes, it makes sense to test only the methods, like Seneca does

**Comment by StarpTech** [comment]
@acehko it was a design decision that hemera isn't transport independent. I won't emulate the NATS messaging logic. NATS function as router, transport layer. You don't have to start NATS if you write your code with testing in mind. Starting with testing your business logic instead to cover it with an integration test.

**Comment by acehko** [comment]
@StarpTech I understand.
But since hemera depends on nats, why is nats not a dependecy of hemera? Right now we need to pass a nats objec to hemera. For that reason we always need to use `hemera-testsuite` for unit testing.

What would be nice is to create a new hemera instance without connecting to nats. That way we could unit test without extra dependencies, and only connect to nats when we run the service in production.
Something like this:
```js
const heemra = new Hemera();
// Connect only in production
hemera.connect(natsURL);
```

**Comment by StarpTech** [comment]
`nats-hemera` means that hemera is tool for nats. Hemera should be small as possible and I seperate the hemera abstraction from the transport. You can also plug your own NATS Server when it match with the interface. I think misunderstood it. Unit test aren't integration tests. You dont need NATS to do it.

**Comment by acehko** [comment]
@StarpTech What you are saying makes sense. I was viewing hemera to be more like seneca than it actually is. As for testing, what I meant was that I want to test methods that were registered with `.add` without the need to run a nats server. I was wrong to call it unit testing.

**Comment by StarpTech** [comment]
@acehko great. btw you has also access to your server method

```js
const payload = hemera.router.lookup({ topic: 'math', cmd: 'add' })
//call add method manually
const request = { a: 1, b: 2 }
payload.action(request, function(err,result) {
//result = 3
})
```

**Comment by StarpTech** [comment]
@acehko https://github.com/hemerajs/hemera/blob/master/examples/unittest.js

**Comment by StarpTech** [comment]
@acehko see the example we provide a small but neat feature to stub the act and add interfaces without to start NATS.
https://github.com/hemerajs/hemera/blob/master/examples/unittest.js
