### ISSUE TITLE
Add nats streaming middleware

### ISSUE THREAD

**Issue by kristianmandrup** [hemerajs/hemera#90]
Before you submit an issue we recommend you drop into the [Gitter community](https://gitter.im/hemerajs/hemera) and ask any questions you have or mention any problems you've had getting started with hemera.

## Context

- [x] nats-hemera (core)
- [ ] hemera-zipkin
- [ ] hemera-store
- [ ] hemera-stats
- [ ] hemera-rabbitmq
- [ ] hemera-nsq
- [ ] hemera-arango-store
- [ ] hemera-sql-store
- [ ] hemera-elasticsearch
- [ ] hemera-couchbase-store
- [ ] hemera-mongo-store
- [ ] hemera-joi
- [ ] hemera-parambulator
- [ ] hemera-msgpack
- [ ] hemera-avro
- [ ] hemera-redis-cache
- [ ] hemera-jwt-auth

## Your Environment
- NATS: X.X.X
- Hemera: X.X.X
- NodeJs: X.X.X
- Environment name and version:
- Operating System and version:

**Comment by StarpTech** [comment]
Hi @kristianmandrup gnats and nats-streaming are two different things. We don't need message persisitence. NATS-Streaming is not mature right now.

**NATS-Streaming:**
- No cluster support ([Issue](https://github.com/nats-io/nats-streaming-server/issues/13))

**Imcompatibility with Gnats**
- No wildcard support (Will break the current interface)

A possible solution is two use both gnats and nats-streaming with one driver because `nats-streaming` rely on `node-nats` but this is not in the roadmap.

**Comment by StarpTech** [comment]
Hi @kristianmandrup nats-streaming is available as bridge

https://github.com/hemerajs/hemera/tree/master/packages/hemera-nats-streaming
